dist: trusty
language: python

python:
  - "3.5"
  
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y llvm-3.5-dev
  
install:
  - pip install -U pip setuptools
  - export LLVM_CONFIG_PATH="`which llvm-config`"
  - $LLVM_CONFIG_PATH --cflags # test llvm-config
  - export LLVMPY_DYNLINK=1
  - pip install -r requirements.txt

script: 
  - py.test --cov .
