dist: trusty
language: python

python:
  - "3.5"
  
before_install:
  - sudo deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main
  - sudo deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main
  - sudo wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get install -y llvm-3.7-dev
  
install:
  - pip install -U pip setuptools
  - export LLVM_CONFIG_PATH="`which llvm-config`"
  - $LLVM_CONFIG_PATH --cflags # test llvm-config
  - export LLVMPY_DYNLINK=1
  - pip install -r requirements.txt

script: 
  - py.test --cov .
